### ISSUE TITLE
Mention compatible TeX live distribution in RELEASING.md

### ISSUE THREAD

**Issue by xrotwang** [unicode-cookbook/cookbook#3]
If compilation requires lots of packages, it would probably be helpful to mention a [TeX Live](https://en.wikipedia.org/wiki/TeX_Live) you successfully compiled the book with. For all linux based systems this will provide the simplest way to reproduce what you got.

**Comment by bambooforest** [comment]
@xrotwang like this?

We have success compiling the unicde.tex document using the MacTeX 2016 distribution of TeX Live and TeXShop, available at: https://tug.org/mactex/.

https://github.com/unicode-cookbook/cookbook/blob/master/RELEASING.md

**Comment by xrotwang** [comment]
Yes!
