### ISSUE TITLE
Profile spec A3 and B7: Why should the metadata for a profile specify processor internals?

### ISSUE THREAD

**Issue by xrotwang** [unicode-cookbook/cookbook#31]
The spec says 
- in A3 the "tokenization method" and 
- in B7 the "unicode normalization"

should by specified in the metadata. But aren't these things either implementation details or part of the metadata of the profile processor rather than the profile? AFAIKT a profile which doesn't specify any of the context columns could be processed using any method, "global" or "linear", right?

**Comment by bambooforest** [comment]
So instead @xrotwang we prefer leaving this one potentially unspecified, in which case the user can do whatever they way processing-wise? So instead of making it mandatory:

```Further, the metadata file should provide information about the orthogra- phy profile’s structure and contents, including: (vi) its dialect description,7 (vii) the tokenization method (see below), and (ix) proper column descrip- tions,8 which describe how a column should be interpreted and processed (e.g. whether they should be processed as regular expressions; see below).```

We simply make it optional?

**Comment by xrotwang** [comment]
I think the tokenization method should not be specified as part of the orthography profile (or its metadata). In theory, it should be possible to use different tokenization methods with the same profile, right?

**Comment by bambooforest** [comment]
Yes, in theory. I'm a bit confused though -- don't we want to let the user specify how they intend the source to be tokenized given their OP? That's what we're doing in #33 I thought -- specifying if the column should be interpreted as literal graphemes or as regular expression-specified patterns. So here we're saying that the user should not be able to specify whether the tokenization happens globally or linearly -- and that this option should be chosen by the user when using the software, or?

**Comment by xrotwang** [comment]
Yes, doesn't this make sense? If orthography profiles were specific to one particular tokenization method, things would be different. But if this was the case, I wouldn't see much general value in this spec - then it would just be the description of the application config format for the segments package.
